In [2]:
import numpy as np
print(np.linspace(5,10,2))
print(np.linspace(5,10,3))
print(np.linspace(5,10,4))

[ 5. 10.]
[ 5.   7.5 10. ]
[ 5.          6.66666667  8.33333333 10.        ]


### Basic mathematical operations

In [3]:
a=np.array([1,2,3])
b=np.array([1,1,1])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

[2 3 4]
[0 1 2]
[1 2 3]
[1. 2. 3.]
[1 2 3]
[0 0 0]
[1 2 3]


In [4]:
a+1

array([2, 3, 4])

In [5]:
a+[1]

array([2, 3, 4])

In [10]:
b1 = np.full((3,4,2),2)
b2 = 1
b3 = np.array([2,3])
b4 = np.array([[1],[2]])

In [11]:
print(b3.shape,b4.shape)
b3+b4

(2,) (2, 1)


array([[3, 4],
       [4, 5]])

In [21]:
b1 = np.full((3,4,2),2)
b5 = np.full((1,3,1,2),4)

In [22]:
b1+b5

array([[[[6, 6],
         [6, 6],
         [6, 6],
         [6, 6]],

        [[6, 6],
         [6, 6],
         [6, 6],
         [6, 6]],

        [[6, 6],
         [6, 6],
         [6, 6],
         [6, 6]]]])

In [14]:
(b1+b5).shape

(1, 3, 4, 2)

In [24]:
a = np.arange(25)
print(a[:25])
print(a[5:10])
print(a[2:24:5])
print(a[1])
print(a[-1])
print(a[[2,5,9]])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[5 6 7 8 9]
[ 2  7 12 17 22]
1
24
[2 5 9]


### Random Package

In [32]:
np.random.randint(7,10,(2,2))

array([[8, 7],
       [9, 9]])

In [61]:
np.random.randint(1,100,(2,2))

array([[36, 68],
       [28, 47]])

In [63]:
np.random.random((4,5))

array([[0.95096236, 0.73755226, 0.22990653, 0.98501258, 0.48000691],
       [0.6403963 , 0.08949634, 0.19046176, 0.27583487, 0.4435591 ],
       [0.9929528 , 0.03452407, 0.66380171, 0.70309367, 0.79288996],
       [0.12695227, 0.07405865, 0.6643888 , 0.89284596, 0.34883396]])

In [65]:
np.random.randn()

-0.4835913018336546

In [64]:
np.random.normal()

-1.0203477763732678

In [66]:
np.random.randn(2,3)

array([[-1.31261926, -1.77984177,  0.02835191],
       [ 1.30859338,  0.97801564,  1.45444592]])

In [67]:
np.random.normal((2,3))

array([1.54376793, 2.33268176])

In [68]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

In [69]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

In [70]:
a1=np.array([10,20,30,40,50])
np.min(a1)

10

In [71]:
np.sum(a1)

150

In [72]:
np.max(a1)

50

In [73]:
np.mean(a1)

30.0

In [74]:
np.median(a1)

30.0

In [75]:
np.quantile(a1,0.25)

20.0

In [76]:
np.quantile(a1,0.5)

30.0

In [77]:
np.quantile(a1,0.75)

40.0

In [78]:
a1=np.array([[1,2],[1,2]])
a1
print(np.sum(a1,axis=0))
print(np.sum(a1,axis=1))

[2 4]
[3 3]


In [79]:
print(np.sum(a1,axis=1,keepdims=True))

[[3]
 [3]]


In [80]:
def min(a,b):
    '''this the machine learning course'''
    return a,b

In [82]:
help(min)

Help on function min in module __main__:

min(a, b)
    this the machine learning course



In [5]:
import vineethtxt
vineethtxt.name

'vineeth'

In [6]:
if -40:
    print("your name")

your name


In [7]:
bool(' ')

True

In [8]:
bool('')

False

In [10]:
if ' ':
    print("vineeth")
else:
    print("gitam")

vineeth


In [11]:
list={1:2,3:4,5:6}
print([i**0.5 for i in list])

[1.0, 1.7320508075688772, 2.23606797749979]
